### ISSUE TITLE
Add support for Rider 2024.3 EAP2

### ISSUE THREAD

**Issue by bassepeder** [Socolin/NSubstituteComplete#11]

**Comment by cpirtea-bun** [comment]
2024.3 is now in General Release. Can we please get the plugin updated?

**Comment by Socolin** [comment]
Yes I'll try to upgrade as soon as I find some times

**Comment by andersklepaker** [comment]
Much appreciated, @Socolin ❤️

**Comment by Socolin** [comment]
The version was updated and will be available through the jetbrains marketplace during next week, if you need it now you can download it here an manually install it.
[nsubstitutecomplete-2024.3.0.zip](https://github.com/user-attachments/files/17791944/nsubstitutecomplete-2024.3.0.zip)
