### ISSUE TITLE
Selected autocompleted code disappears

### ISSUE THREAD

**Issue by jesubiag** [Socolin/NSubstituteComplete#2]
When trying to use autocomplete, after selecting an option from the plugin to autocomplete the code, it seems to do it but the code disappears immediately. I didn't found any error or log in the IDE.

IDE version: JetBrains Rider 2021.1.2
Plugin version: 1.4.1

Example video:
https://user-images.githubusercontent.com/4550591/117975776-6d022e80-b305-11eb-93a9-392e72355c61.mov

Edit: typo

**Comment by provegard** [comment]
I'm experiencing the same problem. The Rider log contains:

```
HResult = E_POINTER=COR_E_NULLREFERENCE=80004003
Source = JetBrains.ReSharper.Psi.CSharp
StackTraceString = 
  at JetBrains.ReSharper.Psi.CSharp.CSharpElementFactory.GetInstance(ITreeNode element, Boolean applyCodeFormatter)
     at ReSharperPlugin.NSubstituteComplete.CompletionProvider.Behaviors.InsertNSubstituteArgumentBehavior.Accept(ITextControl textControl, DocumentRange nameRange, LookupItemInsertType insertType, Suffix suffix, ISolution solution, Boolean keepCaretStill) in /home/socolin/RiderProjects/NSubstituteComplete/src/dotnet/ReSharperPlugin.NSubstituteComplete/CompletionProvider/Behaviors/InsertNSubstituteArgumentBehavior.cs:line 41
     at JetBrains.ReSharper.Feature.Services.CodeCompletion.Infrastructure.AspectLookupItems.BaseInfrastructure.LookupItem`1.Accept(ITextControl textControl, DocumentRange nameRange, LookupItemInsertType insertType, Suffix suffix, ISolution solution, Boolean keepCaretStill)
     at JetBrains.ReSharper.Feature.Services.CodeCompletion.Infrastructure.LookupItems.LookupItemCompletor.CompleteItem(Action executeInsideCommandScope)
     at JetBrains.ReSharper.Host.Features.Completion.CompletionHost.<CompleteItemAsync>d__37.MoveNext()
  --- End of stack trace from previous location where exception was thrown ---
     at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
     at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
     at JetBrains.ReSharper.Host.Features.Completion.CompletionHost.<HandleComplete>d__35.MoveNext()
```

**Comment by Socolin** [comment]
Hello,

Does this happen frequently ? 
Does it happens again and again for the same one ?

I don't have much time recently, if you have a repro project I think I could fix more quickly.

**Comment by jesubiag** [comment]
Hi. It happens every time with that specific feature. Autocomplete in other parts of the code works fine.
I can't give you at the moment a project.

**Comment by Socolin** [comment]
Hello,

It should be fix in the next version (pending validation), it should be available soon.

**Comment by ghost** [comment]
I have the same problem with the new Version 1.4.2 !

see
--- EXCEPTION #1/2 [Exception]
Message = “Scenario not supported, please report this on github: https://github.com/Socolin/NSubstituteComplete/issues”
ExceptionPath = Root.InnerException
ClassName = System.Exception
Data.ThreadLocalDebugInfo = “
  endpoint `MainProtocol.SolutionModel.solutions.[1].documentsOperationModel.documents.[RdProjectFileDocumentId (  projectModelElementId = 13183  filePath = "C:/git/RollTester/test/RollTester.Simulation.Tests/Provider/SampleResultFileAdapter/SampleResultFileAdapterTests.cs"  protocol = "file")].textControls.[TextControlId (  documentId = RdProjectFileDocumentId (  projectModelElementId = 13183  filePath = "C:/git/RollTester/test/RollTester.Simulation.Tests/Provider/SampleResultFileAdapter/SampleResultFileAdapterTests.cs"  protocol = "file")  tabIndex = 1  kind = EditorTab  clientId = "Host")].completionModel.completionSession.$.session.complete` (6696728496423056363)
   -> RdDispatcher::FlushAll
”
HResult = COR_E_EXCEPTION=80131500
Source = ReSharperPlugin.NSubstituteComplete
StackTraceString = “
  bei ReSharperPlugin.NSubstituteComplete.CompletionProvider.Behaviors.InsertNSubstituteArgumentBehavior.Accept(ITextControl textControl, DocumentRange nameRange, LookupItemInsertType insertType, Suffix suffix, ISolution solution, Boolean keepCaretStill) in /home/socolin/RiderProjects/NSubstituteComplete/src/dotnet/ReSharperPlugin.NSubstituteComplete/CompletionProvider/Behaviors/InsertNSubstituteArgumentBehavior.cs:Zeile 73.
     bei JetBrains.ReSharper.Feature.Services.CodeCompletion.Infrastructure.AspectLookupItems.BaseInfrastructure.LookupItem`1.Accept(ITextControl textControl, DocumentRange nameRange, LookupItemInsertType insertType, Suffix suffix, ISolution solution, Boolean keepCaretStill)
     bei JetBrains.ReSharper.Feature.Services.CodeCompletion.Infrastructure.LookupItems.LookupItemCompletor.CompleteItem(Action executeInsideCommandScope)
     bei JetBrains.ReSharper.Host.Features.Completion.CompletionHost.<CompleteItemAsync>d__37.MoveNext()
  --- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
     bei System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
     bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
     bei JetBrains.ReSharper.Host.Features.Completion.CompletionHost.<HandleComplete>d__35.MoveNext()
”

--- Outer ---

--- EXCEPTION #2/2 [LoggerException]
Message = “Scenario not supported, please report this on github: https://github.com/Socolin/NSubstituteComplete/issues”
ExceptionPath = Root
ClassName = JetBrains.Util.LoggerException
InnerException = “Exception #1 at Root.InnerException”
HResult = COR_E_APPLICATION=80131600
StackTraceString = “
  bei JetBrains.Util.LoggerBase.Log(LoggingLevel level, String message, Exception ex)
     bei JetBrains.Util.Logging.Logger.LogException(Exception ex)
     bei JetBrains.ReSharper.Host.Features.Completion.CompletionHost.<HandleComplete>d__35.MoveNext()
     bei System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)
     bei JetBrains.ReSharper.Host.Features.Completion.CompletionHost.HandleComplete(CompleteData data, ITextControl textControl)
     bei JetBrains.ReSharper.Host.Features.Completion.CompletionHost.<CompleteHandlerAsync>d__23.MoveNext()
     bei System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)
     bei JetBrains.ReSharper.Host.Features.Completion.CompletionHost.CompleteHandlerAsync(HostTextControl textControl, CompleteData completeData)
     bei JetBrains.ReSharper.Host.Features.Completion.CompletionHost.<>c__DisplayClass22_0.<CalculateItems>b__4(Lifetime arg1, CompleteData completeData)
     bei JetBrains.Rd.Tasks.RdCall`2.OnWireReceived(UnsafeReader reader)
     bei JetBrains.Rd.Impl.MessageBroker.Execute(IRdWireable reactive, Byte[] msg)
     bei JetBrains.Platform.RdFramework.Impl.RdDispatcher.FlushAll()
     bei JetBrains.Threading.ReentrancyGuard.<>c__DisplayClass31_0.<Queue>b__0()
     bei JetBrains.Threading.ReentrancyGuard.Execute(String name, Action action)
     bei JetBrains.Threading.ReentrancyGuard.ExecutePendingActions()
     bei JetBrains.Threading.JetDispatcher.Closure.Execute()
     bei JetBrains.Util.Concurrency.WinJetDispatcher.ProcessQueue(Int32 nMinBucket)
     bei System.Windows.Threading.DispatcherOperation.InvokeDelegateCore()
     bei System.Windows.Threading.DispatcherOperation.InvokeImpl()
     bei MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
     bei System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
     bei System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
     bei System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
     bei MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
     bei System.Windows.Threading.DispatcherOperation.Invoke()
     bei System.Windows.Threading.Dispatcher.ProcessQueue()
     bei System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
     bei MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
     bei MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
     bei System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
     bei System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
     bei System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
     bei MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
     bei JetBrains.Interop.WinApi.User32Dll.DispatchMessageW(MSG* lpmsg)
     bei JetBrains.Interop.WinApi.User32Dll.DispatchMessageW(MSG* lpmsg)
     bei JetBrains.Util.Concurrency.WinJetDispatcher.WinJetDispatcherStaticMethods.InternalPumpMessagesOnce()
     bei JetBrains.Util.Concurrency.WinJetDispatcher.WinJetDispatcherStaticMethods.JetBrains.Util.Concurrency.IJetDispatcherStaticMethods.Run()
     bei JetBrains.ReSharper.Host.Product.RiderMain.Main(Lifetime lifetime, IRiderSettings settings, ILogger logger, ProtocolComponent protocol, RdShellModel shellModel, ApplicationShutdownRequests shutdownRequests)
     bei System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
     bei System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
     bei System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
     bei JetBrains.Application.Environment.RunsPublicStaticIntMain.<>c__DisplayClass0_0.<.ctor>b__0()
     bei JetBrains.Util.Logging.Logger.Catch(Action action)
     bei JetBrains.Threading.JetDispatcher.Closure.Execute()
     bei JetBrains.Util.Concurrency.WinJetDispatcher.ProcessQueue(Int32 nMinBucket)
     bei System.Windows.Threading.DispatcherOperation.InvokeDelegateCore()
     bei System.Windows.Threading.DispatcherOperation.InvokeImpl()
     bei MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
     bei System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
     bei System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
     bei System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
     bei MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
     bei System.Windows.Threading.DispatcherOperation.Invoke()
     bei System.Windows.Threading.Dispatcher.ProcessQueue()
     bei System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
     bei MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
     bei MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
     bei System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
     bei System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
     bei System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
     bei MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
     bei MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
     bei MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
     bei System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
     bei JetBrains.Application.Environment.IJetHostEx.<>c__DisplayClass2_0.<RunHostMessageLoop>b__0(Lifetime lifetime)
     bei JetBrains.Lifetimes.Lifetime.Using(Action`1 action)
     bei JetBrains.Application.Environment.IJetHostEx.RunHostMessageLoop(IComponentContainer containerEnv)
     bei JetBrains.Application.Environment.HostParameters.JetHostParametersCaller.RunMainLoop(ComponentContainer containerEnv)
     bei JetBrains.Application.Environment.JetEnvironment.InternalRun(JetHostParametersCaller host, ComponentContainer containerEnv)
     bei JetBrains.Application.Environment.JetEnvironment.CreateAndRun(Full hostparams)
     bei JetBrains.ReSharper.Host.Product.RiderBackendProgram.MainX(Assembly assembly, HostInfo hostInfo, String[] args)
     bei JetBrains.ReSharper.Host.Product.RiderBackendProgram.<>c.<Main>b__3_0(Lifetime lifetime)
     bei JetBrains.Lifetimes.Lifetime.Using[T](Func`2 action)
     bei JetBrains.ReSharper.Host.Product.RiderBackendProgram.Main()
     bei System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
     bei System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
     bei System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
     bei JetBrains.Launcher.Msil.LauncherManagedCore.JetBrains.Launcher.Msil.ILauncherManagedCore.InvokeManagedMethod(String sAssemblyName, String sAssemblyFile, String sClassName, String sMethodName, Int32& phrExitCode, String& bsFailureMessageShort, String& bsFailureMessageLong)
”
, throwable=com.jetbrains.rdclient.util.BackendException: Scenario not supported, please report this on github: https://github.com/Socolin/NSubstituteComplete/issues

--- EXCEPTION #1/2 [Exception]
Message = “Scenario not supported, please report this on github: https://github.com/Socolin/NSubstituteComplete/issues”
ExceptionPath = Root.InnerException
ClassName = System.Exception
Data.ThreadLocalDebugInfo = “
  endpoint `MainProtocol.SolutionModel.solutions.[1].documentsOperationModel.documents.[RdProjectFileDocumentId (  projectModelElementId = 13183  filePath = "C:/git/RollTester/test/RollTester.Simulation.Tests/Provider/SampleResultFileAdapter/SampleResultFileAdapterTests.cs"  protocol = "file")].textControls.[TextControlId (  documentId = RdProjectFileDocumentId (  projectModelElementId = 13183  filePath = "C:/git/RollTester/test/RollTester.Simulation.Tests/Provider/SampleResultFileAdapter/SampleResultFileAdapterTests.cs"  protocol = "file")  tabIndex = 1  kind = EditorTab  clientId = "Host")].completionModel.completionSession.$.session.complete` (6696728496423056363)
   -> RdDispatcher::FlushAll
”
HResult = COR_E_EXCEPTION=80131500
Source = ReSharperPlugin.NSubstituteComplete
StackTraceString = “
  bei ReSharperPlugin.NSubstituteComplete.CompletionProvider.Behaviors.InsertNSubstituteArgumentBehavior.Accept(ITextControl textControl, DocumentRange nameRange, LookupItemInsertType insertType, Suffix suffix, ISolution solution, Boolean keepCaretStill) in /home/socolin/RiderProjects/NSubstituteComplete/src/dotnet/ReSharperPlugin.NSubstituteComplete/CompletionProvider/Behaviors/InsertNSubstituteArgumentBehavior.cs:Zeile 73.
     bei JetBrains.ReSharper.Feature.Services.CodeCompletion.Infrastructure.AspectLookupItems.BaseInfrastructure.LookupItem`1.Accept(ITextControl textControl, DocumentRange nameRange, LookupItemInsertType insertType, Suffix suffix, ISolution solution, Boolean keepCaretStill)
     bei JetBrains.ReSharper.Feature.Services.CodeCompletion.Infrastructure.LookupItems.LookupItemCompletor.CompleteItem(Action executeInsideCommandScope)
     bei JetBrains.ReSharper.Host.Features.Completion.CompletionHost.<CompleteItemAsync>d__37.MoveNext()
  --- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
     bei System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
     bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
     bei JetBrains.ReSharper.Host.Features.Completion.CompletionHost.<HandleComplete>d__35.MoveNext()
”

--- Outer ---

--- EXCEPTION #2/2 [LoggerException]
Message = “Scenario not supported, please report this on github: https://github.com/Socolin/NSubstituteComplete/issues”
ExceptionPath = Root
ClassName = JetBrains.Util.LoggerException
InnerException = “Exception #1 at Root.InnerException”
HResult = COR_E_APPLICATION=80131600
StackTraceString = “
  bei JetBrains.Util.LoggerBase.Log(LoggingLevel level, String message, Exception ex)
     bei JetBrains.Util.Logging.Logger.LogException(Exception ex)
     bei JetBrains.ReSharper.Host.Features.Completion.CompletionHost.<HandleComplete>d__35.MoveNext()
     bei System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)
     bei JetBrains.ReSharper.Host.Features.Completion.CompletionHost.HandleComplete(CompleteData data, ITextControl textControl)
     bei JetBrains.ReSharper.Host.Features.Completion.CompletionHost.<CompleteHandlerAsync>d__23.MoveNext()
     bei System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)
     bei JetBrains.ReSharper.Host.Features.Completion.CompletionHost.CompleteHandlerAsync(HostTextControl textControl, CompleteData completeData)
     bei JetBrains.ReSharper.Host.Features.Completion.CompletionHost.<>c__DisplayClass22_0.<CalculateItems>b__4(Lifetime arg1, CompleteData completeData)
     bei JetBrains.Rd.Tasks.RdCall`2.OnWireReceived(UnsafeReader reader)
     bei JetBrains.Rd.Impl.MessageBroker.Execute(IRdWireable reactive, Byte[] msg)
     bei JetBrains.Platform.RdFramework.Impl.RdDispatcher.FlushAll()
     bei JetBrains.Threading.ReentrancyGuard.<>c__DisplayClass31_0.<Queue>b__0()
     bei JetBrains.Threading.ReentrancyGuard.Execute(String name, Action action)
     bei JetBrains.Threading.ReentrancyGuard.ExecutePendingActions()
     bei JetBrains.Threading.JetDispatcher.Closure.Execute()
     bei JetBrains.Util.Concurrency.WinJetDispatcher.ProcessQueue(Int32 nMinBucket)
     bei System.Windows.Threading.DispatcherOperation.InvokeDelegateCore()
     bei System.Windows.Threading.DispatcherOperation.InvokeImpl()
     bei MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
     bei System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
     bei System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
     bei System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
     bei MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
     bei System.Windows.Threading.DispatcherOperation.Invoke()
     bei System.Windows.Threading.Dispatcher.ProcessQueue()
     bei System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
     bei MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
     bei MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
     bei System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
     bei System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
     bei System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
     bei MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
     bei JetBrains.Interop.WinApi.User32Dll.DispatchMessageW(MSG* lpmsg)
     bei JetBrains.Interop.WinApi.User32Dll.DispatchMessageW(MSG* lpmsg)
     bei JetBrains.Util.Concurrency.WinJetDispatcher.WinJetDispatcherStaticMethods.InternalPumpMessagesOnce()
     bei JetBrains.Util.Concurrency.WinJetDispatcher.WinJetDispatcherStaticMethods.JetBrains.Util.Concurrency.IJetDispatcherStaticMethods.Run()
     bei JetBrains.ReSharper.Host.Product.RiderMain.Main(Lifetime lifetime, IRiderSettings settings, ILogger logger, ProtocolComponent protocol, RdShellModel shellModel, ApplicationShutdownRequests shutdownRequests)
     bei System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
     bei System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
     bei System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
     bei JetBrains.Application.Environment.RunsPublicStaticIntMain.<>c__DisplayClass0_0.<.ctor>b__0()
     bei JetBrains.Util.Logging.Logger.Catch(Action action)
     bei JetBrains.Threading.JetDispatcher.Closure.Execute()
     bei JetBrains.Util.Concurrency.WinJetDispatcher.ProcessQueue(Int32 nMinBucket)
     bei System.Windows.Threading.DispatcherOperation.InvokeDelegateCore()
     bei System.Windows.Threading.DispatcherOperation.InvokeImpl()
     bei MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
     bei System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
     bei System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
     bei System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
     bei MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
     bei System.Windows.Threading.DispatcherOperation.Invoke()
     bei System.Windows.Threading.Dispatcher.ProcessQueue()
     bei System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
     bei MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
     bei MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
     bei System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
     bei System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
     bei System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
     bei MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
     bei MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
     bei MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
     bei System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
     bei JetBrains.Application.Environment.IJetHostEx.<>c__DisplayClass2_0.<RunHostMessageLoop>b__0(Lifetime lifetime)
     bei JetBrains.Lifetimes.Lifetime.Using(Action`1 action)
     bei JetBrains.Application.Environment.IJetHostEx.RunHostMessageLoop(IComponentContainer containerEnv)
     bei JetBrains.Application.Environment.HostParameters.JetHostParametersCaller.RunMainLoop(ComponentContainer containerEnv)
     bei JetBrains.Application.Environment.JetEnvironment.InternalRun(JetHostParametersCaller host, ComponentContainer containerEnv)
     bei JetBrains.Application.Environment.JetEnvironment.CreateAndRun(Full hostparams)
     bei JetBrains.ReSharper.Host.Product.RiderBackendProgram.MainX(Assembly assembly, HostInfo hostInfo, String[] args)
     bei JetBrains.ReSharper.Host.Product.RiderBackendProgram.<>c.<Main>b__3_0(Lifetime lifetime)
     bei JetBrains.Lifetimes.Lifetime.Using[T](Func`2 action)
     bei JetBrains.ReSharper.Host.Product.RiderBackendProgram.Main()
     bei System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
     bei System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
     bei System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
     bei JetBrains.Launcher.Msil.LauncherManagedCore.JetBrains.Launcher.Msil.ILauncherManagedCore.InvokeManagedMethod(String sAssemblyName, String sAssemblyFile, String sClassName, String sMethodName, Int32& phrExitCode, String& bsFailureMessageShort, String& bsFailureMessageLong)
”

	at com.jetbrains.rdclient.protocol.components.RdClientProtocolComponent$2.invoke(RdClientProtocolComponent.kt:49)
	at com.jetbrains.rdclient.protocol.components.RdClientProtocolComponent$2.invoke(RdClientProtocolComponent.kt:24)
	at com.jetbrains.rd.util.reactive.Signal.fire(Signal.kt:32)
	at com.jetbrains.rd.framework.impl.RdSignal.onWireReceived(RdSignal.kt:42)
	at com.jetbrains.rd.framework.MessageBroker$invoke$2$2.invoke(MessageBroker.kt:56)
	at com.jetbrains.rd.framework.MessageBroker$invoke$2$2.invoke(MessageBroker.kt:11)
	at com.jetbrains.rd.framework.impl.ProtocolContexts.readMessageContextAndInvoke(ProtocolContexts.kt:151)
	at com.jetbrains.rd.framework.MessageBroker$invoke$2.invoke(MessageBroker.kt:55)
	at com.jetbrains.rd.framework.MessageBroker$invoke$2.invoke(MessageBroker.kt:11)
	at com.jetbrains.rdclient.protocol.RdDispatcher.a(RdDispatcher.kt:96)
	at com.jetbrains.rdclient.protocol.RdDispatcher.access$flushAll(RdDispatcher.kt:17)
	at com.jetbrains.rdclient.protocol.RdDispatcher$flushAllRunnable$1.run(RdDispatcher.kt:22)
	at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:218)
	at com.intellij.openapi.application.TransactionGuardImpl.access$200(TransactionGuardImpl.java:21)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:200)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:781)
	at com.intellij.openapi.application.impl.ApplicationImpl.lambda$invokeLater$4(ApplicationImpl.java:319)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:84)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:133)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:46)
	at com.intellij.openapi.application.impl.FlushQueue$FlushNow.run(FlushQueue.java:189)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:969)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:839)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:449)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:808)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$9(IdeEventQueue.java:448)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:781)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:496)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
]

**Comment by Socolin** [comment]
@patrickfritzkl Can you copy the expression where you are trying to use the completion ? from the start of the lien to the `;` (you can rename function/field name if it's confidential code) I'm going to need this to support it

**Comment by ghost** [comment]
Hi, I made a gif... 
![NSubComp](https://user-images.githubusercontent.com/45970411/125895846-e3c635da-6f8c-4822-b5fe-d3087791c45a.gif)

**Comment by Socolin** [comment]
> Hi, I made a gif...

Thanks, this should be fix in the next version.

**Comment by Socolin** [comment]
Hello,

Since I did not get any feedback I'm assuming this is fix
