### ISSUE TITLE
Plugin incompatible with Rider EAP 2021.3

### ISSUE THREAD

**Issue by vardansargsyan92** [Socolin/NSubstituteComplete#3]
An early access of rider has been released with UWP app debugging support which is nice. The bad news is that the plugin "
NSubstituteComplete" is not compatible with the new rider. So it would be nice to see the plugin support for rider 2021.3

**Comment by Socolin** [comment]
It should now be available

**Comment by vardansargsyan92** [comment]
@Socolin  thanks a lot

**Comment by vardansargsyan92** [comment]
thank you
