### ISSUE TITLE
Settings page doesn't work in 2021.3.1

### ISSUE THREAD

**Issue by PavelFischerCoupa** [Socolin/NSubstituteComplete#4]
Hello,

with rider update I expect the same issue as in https://github.com/Socolin/NSubstituteComplete/issues/1
Rider version 2021.3.1, plugin version 1.6.0

**Comment by Socolin** [comment]
It should be fixed in 1.6.1

**Comment by PavelFischerCoupa** [comment]
Can confirm. It works. Thank you!
